name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.2
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /var/www/myproject/
        remote_host: 3.110.197.208
        remote_user: debian
        remote_key: ${{ secrets.REMOTE_KEY }}
